runtime: python
env: flex
entrypoint: gunicorn -b :$PORT track_cov.wsgi --log-level=DEBUG
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

runtime_config:
  python_version: 3.6

env_variables:
  google_project_id: ""
  fcm_server_key: ""
  JWT_SECRET: ""
  DEBUG: False